kind: Deployment
apiVersion: apps/v1
metadata:
  name: image-uploader
  namespace: ose4-pipeline-cli
  labels:
    app: image-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-uploader
  template:
    metadata:
      labels:
        app: image-uploader
    spec:
      containers:
        - name: image-uploader
          image: >-
            image-registry.openshift-image-registry.svc:5000/ose4-pipeline-cli/image-uploader:latest
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
