apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: deploy-example
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: deploy-example
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: deploy-example
  spec:
    replicas: 2
    selector:
      deploymentconfig: deploy-example
    strategy:
      # We set the type of strategy to Recreate, which means that it will be scaled down prior to being scaled up
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: deploy-example
      spec:
        containers:
        - image: openshift/deployment-example:v1
          name: deployment-example
          ports:
          - containerPort: 8080
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - deployment-example
        from:
          kind: ImageStreamTag
          name: deploy-example:latest
      type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: deploy-example
  spec:
    dockerImageRepository: openshift/deployment-example
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: deploy-example
  spec:
    to:
      kind: Service
      name: deploy-example
